#!/bin/bash
echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[41m \033[37m        ⇱ SSH PLUS MANAGER - IRAN AETEAM ⇲        \033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo ""
function lock_user() {
    read -p "Enter username: " username
    check_user_exist=$(grep -w $username /etc/passwd | cut -d: -f1)
    if [[ $check_user_exist == $username ]]; then
        chage -E 0 $username
        echo "$username locked successfully!"
        echo "$username" >> /root/AET-UL.txt
    else
        echo "$username not found. Please try again."
    fi
}

function unlock_user() {
    read -p "Enter username: " username
    check_user_exist=$(grep -w $username /etc/passwd | cut -d: -f1)
    if [[ $check_user_exist == $username ]]; then
        chage -E -1 $username
        echo "$username unlocked successfully!"
        sed -i "/$username/d" /root/AET-UL.txt
    else
        echo "$username not found. Please try again."
    fi
}

function show_locked_users() {
    if [ -f "/root/AET-UL.txt" ]; then
        echo "Locked users:"
        cat /root/AET-UL.txt
    else
        echo "No locked users found."
    fi
}

function show_user_devices() {
    read -p "Enter username: " username
    check_user_exist=$(grep -w $username /etc/passwd | cut -d: -f1)
    if [[ $check_user_exist == $username ]]; then
        echo "Devices connected by $username:"
        who | grep $username > /root/AET-Devices.txt
        cat /root/AET-Devices.txt
    else
        echo "$username not found. Please try again."
    fi
}

function show_device_file() {
    echo "Content of AET-Devices.txt:"
    cat /root/AET-Devices.txt
}

function clear_device_file() {
    > /root/AET-Devices.txt
    echo "Device file cleared!"
}

echo -e "\033[1;33mLock/Unlock USERS\033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;32m [1] \033[1;31m• \033[1;33mLock User\033[0m"
echo -e "\033[1;32m [2] \033[1;31m• \033[1;33mUnlock User\033[0m"
echo -e "\033[1;32m [3] \033[1;31m• \033[1;33mShow locked users\033[0m"
echo -e "\033[1;32m [4] \033[1;31m• \033[1;33mShow user devices\033[0m"
echo -e "\033[1;32m [5] \033[1;31m• \033[1;33mExit\033[0m"
echo ""
echo -e "\033[1;32m [6] \033[1;31m• \033[1;33mShow device file\033[0m"
echo -e "\033[1;32m [7] \033[1;31m• \033[1;33mClear device file\033[0m"
echo ""
read -p "Enter option number: " option

case $option in
1) lock_user;;
2) unlock_user;;
3) show_locked_users;;
4) show_user_devices;;
5) show_device_file;;
6) clear_device_file;;
7) exit;;
*) echo "Invalid option. Please try again.";;
esac
